variables:
  BUILD_ENV: "pd-build-mgmt-373"
  RUNNING_ENV: "pd-ci-mgmt-373"
  PYTHON_PATH: "/D/Projects/PD/softwares/python/python-3.7.3"
  BASE_PYTHON_PATH: "D:/Projects/PD/softwares/python/python-3.7.3"
  VE_PATH: "${CI_BUILDS_DIR}/${RUNNING_ENV}/Scripts/activate.ps1"
  NSSM_PATH: "/D/Projects/PD/softwares/nssm/nssm-2.24/win64/nssm.exe"
  SERVICE_NAME: "pd-ci-mgmt"
  PACKAGE: "pd-mgmt"
#   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
#   CI_DEBUG_TRACE: "false"


stages:
  - test
  - sonar-scan
  - build
  - deploy
  - build-test
  - deploy-test
default:
  before_script:
    - sh etmfa/ci_scripts/create_venv.sh
    - . $VE_PATH

flake8:
  tags:
    - pd-dev-windows-ml01q
  stage: test
  script:
    - flake8 --ignore=E etmfa
  allow_failure: true # Remove it, when ready
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "dev"

unit-tests:
  tags:
      - pd-dev-windows-ml01q
  stage: test
  before_script:
    - . $VE_PATH
  script:
    - python -m pytest --cov=./ --cov-report xml -v --junitxml="test_results.xml"

  artifacts:
      paths:
      - test_results.xml
      - coverage.xml
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "dev"
      
Perform Sonarqube Analysis and quality gate:  
  image: sonarsource/sonar-scanner-cli
  stage: sonar-scan
  only:
    - branches
    - tags
  before_script:
    - echo "Setting up for Sonarqube Analysis on $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - openssl s_client -connect   usadc-vspsq01.quintiles.net:443 | keytool -import -noprompt -alias sonarqbue_test -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit
  script:
    - echo "Running Sonarqube Analysis on $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - sh scripts/sonarqube.sh branch > /tmp/sonar.log
    - cat /tmp/sonar.log
    - echo "Running Sonarqube quality gate on $CI_COMMIT_REF_NAME branch"
    - sh scripts/qualitygate.sh
  allow_failure: true    
  tags:
    - ca2ugitla006p-D4
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "dev" 
      

build:
  tags:
    - pd-dev-windows-ml01q
  stage: build
  before_script:
    - . $VE_PATH  
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "dev"

deploy-dev:
  tags:
    - pd-dev-windows-ml01q
  stage: deploy
  variables:
    VERIFICATION_URL: "http://ca2spdml01q:9001/pd/api/health"
  script:
    - sh etmfa/ci_scripts/deploy.sh dist
  environment:
    name: dev
  only:
    refs:
      - develop
    variables: 
      - $ENVIRONMENT== "dev"
      
build:
  tags:
    - pd-test-windows-ml101q
  stage: build-test
  before_script:
    - . $VE_PATH  
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "test"

deploy-test:
  tags:
    - pd-test-windows-ml101q
  stage: deploy-test
  variables:
    VERIFICATION_URL: "http://ca2spdml101q:9001/pd/api/health"
  script:
    - sh etmfa/ci_scripts/deploy.sh dist
  environment:
    name: test
  only:
    refs:
      - develop
    variables:
      - $ENVIRONMENT== "test"
  
      
      
      
      
      



 