DEBUG: True
mquser: 'guest'
mqpswd: 'guest'
mqhost: 'ca2spdml01q'
mqport: 5672
MESSAGE_BROKER_EXCHANGE: 'PD'
LOGSTASH_HOST: 'ca2spdml01q'
LOGSTASH_PORT: 5959
ENABLE_WORK_FLOW_RUNNER: False
DFS_UPLOAD_FOLDER: '//quintiles.net/enterprise/Services/protdigtest/pilot_iqvxml'
SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://u1149489:pddevQ0pgrg==@10.3.67.93:5432/pd_dev'
# SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://postgres:postgres@localhost/postgres'
#SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://dig_team:pd_test_FSDRFJEDFjfdfj6823#@10.3.64.46:5432/pd_test'

PD_UI_LINK: 'https://protocoldigitalization-ui.work.iqvia.com/dashboard'
#pd ui backend url
# User Authentication
AUTH_DETAILS: {'ypd_api_dev': '$pbkdf2-sha256$8000$yfn/n3Oudc75Pw$A7BQFNmip/A/VqQcQphknV32gdGmFHzq56jjBHN0lXY',
                'ypd_unit_test': '$pbkdf2-sha256$8000$MqZ0jnGO8d77fw$7tT5b7tJbmV0ofz97G75mAUPeDrf5O8ythuRfO6vrWo'}

UNIT_TEST_HEADERS: {"X-API-KEY": "ypd_unit_test:!53*URTa$k1j4t^h2~uSseatnai@nr"}

UI_HOST_NAME: 'https://dev-protocoldigitalization-ui.work.iqvia.com'

EMAILS_ENABLED: "True"
FROM_EMAIL: "no_reply_protocol_digization@iqvia.com"
SMTP_HOST: "Qgbl-devmail.work.iqvia.com"
SMTP_PORT: "25"
ELASTIC_DETAILS: { 'ELASTIC_HOST':'ca2spdml04q',
                   'ELASTIC_PORT': '9200',
                   'ELASTIC_INDEX':"pd-index-3"}