import json, logging

class FormattingReconstructionComplete:
	"""
	POCO message response for a reconstruction request from the formatting microservice
	"""

	QUEUE_NAME = 'formatting_reconstruction_complete'

	def from_msg(msg_str):
		"""
		:param _id:  ID of the document translation request
		:param finalDocumentPath:  Fully-qualified path of the final document generated by the formatting reconstruction
		"""
		resp = json.loads(msg_str)

		this = {}
		this['id'] = resp['id']
		this['finalDocumentPath'] = resp['finalDocumentPath']

		return this