import enum

class StatusEnum(enum.Enum):
    ERROR = -1
    CREATED = 0
    DECONSTRUCTION_STARTED = 1
    DECONSTRUCTION_COMPLETED = 2
    TRANSLATION_STARTED = 3
    TRANSLATION_COMPLETED = 4
    RECONSTRUCTION_STARTED = 5
    RECONSTRUCTION_COMPLETED = 6
    COMPLETE = 7