import enum

class StatusEnum(enum.Enum):
    ERROR = -1
    CREATED = 0


    TRIAGE_STARTED = 1
    TRIAGE_COMPLETED = 2
    OCR_STARTED = 3
    OCR_COMPLETED = 4
    CLASSIFICATION_STARTED = 5
    CLASSIFICATION_COMPLETED = 6
    ATTRIBUTEEXTRACTION_STARTED = 7
    ATTRIBUTEEXTRACTION_COMPLETED = 8
    FINALIZATION_STARTED = 9
    FINALIZATION_COMPLETED = 10
    PROCESS_COMPLETED = 11
    FEEDBACK_COMPLETED = 12

# class StatusEnumpercent(enum.Enum):
#     ERROR = -1
#     CREATED = 0
#
#     TRIAGE_STARTED = 0
#     TRIAGE_COMPLETED = 25
#     OCR_STARTED = 30
#     OCR_COMPLETED = 65
#     CLASSIFICATION_STARTED = 70
#     CLASSIFICATION_COMPLETED = 75
#     ATTRIBUTEEXTRACTION_STARTED = 80
#     ATTRIBUTEEXTRACTION_COMPLETED = 85
#     FINALIZATION_STARTED = 90
#     FINALIZATION_COMPLETED = 95
#     PROCESS_COMPLETED = 100