"""empty message

Revision ID: 1d259b2ea64a
Revises: 0c97130ec33e
Create Date: 2018-02-06 13:00:18.841434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1d259b2ea64a'
down_revision = '0c97130ec33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('tms_document_translate', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('tms_document_translate', 'is_deleted')
    # ### end Alembic commands ###
