# """empty message
#
# Revision ID: 8d3c872fdb2f
# Revises:
# Create Date: 2019-09-09 16:46:21.024345
#
# """
# from alembic import op
# import sqlalchemy as sa
#
#
# # revision identifiers, used by Alembic.
# revision = '8d3c872fdb2f'
# down_revision = None
# branch_labels = None
# depends_on = None
#
#
# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('etmfa_processing2')
#     op.drop_table('etmfa_metrics')
#     op.add_column('etmfa_document_metrics', sa.Column('doc_pages', sa.String(length=200), nullable=True))
#     op.add_column('etmfa_document_metrics', sa.Column('doc_segments', sa.String(length=200), nullable=True))
#     op.add_column('etmfa_document_metrics', sa.Column('doc_type', sa.String(length=200), nullable=True))
#     op.add_column('etmfa_document_metrics', sa.Column('doc_type_original', sa.String(length=200), nullable=True))
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('etmfa_document_metrics', 'doc_type_original')
#     op.drop_column('etmfa_document_metrics', 'doc_type')
#     op.drop_column('etmfa_document_metrics', 'doc_segments')
#     op.drop_column('etmfa_document_metrics', 'doc_pages')
#     op.create_table('etmfa_metrics',
#     sa.Column('id', sa.VARCHAR(length=50), nullable=False),
#     sa.Column('total_process_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('queue_wait_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('triage_machine_name', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('triage_version', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('triage_start_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('triage_end_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('triage_proc_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('digitizer_machine_name', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('digitizer_version', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('digitizer_start_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('digitizer_end_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('digitizer_proc_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('classification_machine_name', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('classification_version', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('classification_start_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('classification_end_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('classification_proc_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('att_extraction_machine_name', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('att_extraction_version', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('att_extraction_start_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('att_extraction_end_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('att_extraction_proc_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('finalization_machine_name', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('finalization_version', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('finalization_start_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('finalization_end_time', sa.VARCHAR(length=200), nullable=True),
#     sa.Column('finalization_proc_time', sa.VARCHAR(length=200), nullable=True),
#     sa.PrimaryKeyConstraint('id', name='sys_c006354')
#     )
#     op.create_table('etmfa_processing2',
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('processing_dir', sa.VARCHAR(length=1000), nullable=True),
#     sa.PrimaryKeyConstraint('id', name='sys_c006177')
#     )
#     # ### end Alembic commands ###
